### ISSUE TITLE
Add support New Relic Annotations

### ISSUE THREAD

**Issue by stefanbuck** [launchdarkly/js-client#139]
I'm super interested in the [New Relic annotation](https://docs.launchdarkly.com/docs/newrelic) which sadly is supported in the Java and Ruby SDK only. Will this ever come for the Node.js and JavasScript SDK?

I ended up with a custom implementation, by calling the `allFlags()` and pass the result along with each [Page Action](https://docs.newrelic.com/docs/browser/new-relic-browser/browser-agent-spa-api/add-page-action).

**Comment by eli-darkly** [comment]
Thanks so much for the feedback. We are planning ways to bring LD closer to APM tools like NewRelic this year. We don't have anything to announce right now, but stay tuned.

I'm going to close this issue for now, but we've saved a link to it so that if we are getting closer to implementing this feature in JS, we can reopen the issue and you'll get a notification.
