### ISSUE TITLE
Typescript Typings

### ISSUE THREAD

**Issue by eboto** [launchdarkly/js-client#14]
Would be great to have some typescript typings for this library! (sister of [this issue](https://github.com/launchdarkly/node-client/issues/43))

**Comment by IceCreamYou** [comment]
I submitted typings to DefinitelyTyped: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/11916

The last typings I submitted to DefinitelyTyped were merged the next business day so I am optimistic that this issue can be closed out shortly.

That said, it would be great to have LaunchDarkly team members review the typings to confirm that they are correct and contribute changes when the library's interface changes 😀

**Comment by apucacao** [comment]
Thanks @IceCreamYou — we'll take a look shortly.

**Comment by jkodumal** [comment]
Awesome @IceCreamYou -- I added a few comments to the DT PR.

**Comment by jkodumal** [comment]
BTW, when that gets merged we will be happy to take over maintaining the typings when our library interface is updated.

**Comment by IceCreamYou** [comment]
The PR was merged yesterday so this issue can be closed 😀

**Comment by jkodumal** [comment]
Thanks @IceCreamYou !

**Comment by ISkomorokh** [comment]
Hi guys! I'm trying to use `ldclient-js` in TypeScript > 2.0 project and it would be great to have working typings. At the moment, VS 2017 and VS Code are both complaining that on the import statement. The code works after build, but I can't use intellisense.
![image](https://cloud.githubusercontent.com/assets/1455188/25886778/d414d778-3567-11e7-97c2-dad73cf099ef.png)

I believe this is because of namespace.

Stackoverflow quote: How do I use namespaces with TypeScript external modules?
Let me cite the first sentence:

Do not use "namespaces" in external modules.
Don't do this.
Seriously. Stop.
...

Thanks!

**Comment by dlau** [comment]
@ISkomorokh  thanks for the report. Please see this PR for an update to our typescript definitions https://github.com/launchdarkly/js-client/issues/14 .

We will publish an update to the npm module shortly.
