### ISSUE TITLE
LDClient Doesn't Properly Identify User If Additional Data Isn't Passed

### ISSUE THREAD

**Issue by StephenMP** [launchdarkly/js-client#141]
When initializing the LDClient, if you use an LDUser without additional data other than `key`, the user is not properly identified. For example, let's say in the LD system, I have the following user:

```
{
    key: "abcd-1234",
    email: "fake@email.com"
}
```

Now, let's say I have the segment `Cool Users`. I have a rule that states that anyone with an email ending with `@email.com` is in this segment.

I also have a feature flag`cool-users` that will return `true` if the user is in the segment `Cool Users`. Then, in my typescript, I have the following code:

```typescript
let ldUser: LDUser = {
    key: 'abcd-1234'
};

this.ldClient = initialize(MY_KEY, ldUser);
this.ldClient.on('ready', () => this.flags = this.ldClient.allFlags());
```

In the above example, the 'cool-users' feature flag is `false`.

However, if I modify the typescript to be (notice I added email):

```typescript
let ldUser: LDUser = {
    key: 'abcd-1234',
    email: 'fake@email.com'
};

this.ldClient = initialize(MY_KEY, ldUser);
this.ldClient.on('ready', () => this.flags = this.ldClient.allFlags());
```

Then the 'cool-users' feature flag is `true` like it should be.

Do note that the client DOES identify the user in the LD system and update the user's metadata properly (e.g. if I were to add some custom data, it adds it to the user properly in the LD system); however, it appears it does not fully identify the user properly within the LDClient. In other words, I would expect the client to query the LD system and ask for a user with the given key. If the user exists, it would populate the client's current user with all existing data on that user in the LD system which would include the email address. Then, when I call something like `this.ldClient.variation('cool-users')` or when the client initializes it would return true for my user since their email ends with `@email.com`.

So, in my example, if I were to do the following:

```typescript
let ldUser: LDUser = {
    key: 'abcd-1234'
};

this.ldClient = initialize(MY_KEY, ldUser);
this.ldClient.on('ready', () => this.flags = this.ldClient.allFlags());
```

I would expect the user that exists within the LDClient to be:

```
{
    key: "abcd-1234",
    email: "fake@email.com"
}
```

but it is not. The user that exists within the LDClient is:

```
{
    key: "abcd-1234"
}
```

**NOTE**
I'm not 100% sure this is an issue with the client or with the LD system. In other words, I'm not sure if the LD system isn't properly checking the user information when a call to get the feature flag values is made (i.e. if I pass a user with a key, does the LD system grab the user based on key, then evaluate the user's data, like email, against the rules in place for user segments or does the LD system just take the user provided to the call as is?).

**Comment by eli-darkly** [comment]
Thanks for asking. It's not really a client issue; it's related to how LaunchDarkly works in general.

Users exist as entities within the central LD system _only for data-gathering purposes_. Your dashboard will show you the attributes of users that you've evaluated flags for, because LD receives that information from the SDK; but the converse is not true, that is, the SDK does not query LaunchDarkly as a database for user properties.

As far as the SDK is concerned, the properties of a user are what your code tells the SDK they are. If you use a key you've used before, but you provide a different set of properties other than the key, then those are the properties it will use to evaluate flags. This means that as long as the feature flag configuration remains the same, then the same JS code using the same user properties will reliably receive the same flag values. If it worked the way you're proposing, then the code would behave differently depending on what some other code may have done elsewhere with the same user key.

Is that helpful?

**Comment by StephenMP** [comment]
Yup, that makes sense and validates pretty much what I was thinking on how the LD system works in general. Thanks for the response @eli-darkly :)
