### ISSUE TITLE
De-identify a user?

### ISSUE THREAD

**Issue by alexlatchford** [launchdarkly/js-client#47]
Hey I'm using reactjs and our sign out doesn't actually reload the page. How can I sign out a user? I'm currently doing this, which works but seems a little hacky:

```
ldclient.identify({ key: '', anonymous: false });
```

I'm not after anonymous tracking, thus the `''`. If I pass in `null` or `undefined` I get a 400 from the server, if I don't pass anything the user says logged in.

Any suggestions?

**Comment by apucacao** [comment]
Hi @alexlatchford,

Thanks for reaching out.

We actually use anonymous users ourselves for this scenario, since we still end up collecting events, without polluting our dashboard with "unknown" users.

Is there a reason why you're trying to avoid anonymous tracking?

As for the 400 error, that's bad etiquette on our part. We're going to improve that.

Cheers,
Alexis

**Comment by alexlatchford** [comment]
Ah okay. If that's the convention that's fine by me, I hadn't used the anonymous feature and didn't really want to clutter up our users situation. I'll just throw in some dummy keys and that should fix it, thanks for clarifying!
