### ISSUE TITLE
LDClient.initialize() multiple times on same page

### ISSUE THREAD

**Issue by jasonbarry** [launchdarkly/js-client#50]
Is it okay to use `LDClient.initialize(env, user)` multiple times on the same page for the same env and user? I'm trying to integrate the feature flagging mechanism into a React component. If multiple components are used on the same page, it seems as if the initialize call interferes with other instances. 

Here's some psuedo-code I'm putting in componentDidMount: 

```JS
componentDidMount() {
    const ldclient = LDClient.initialize(this.env, this.user);
    ldclient.on('ready', () => {
        console.log(`Getting feature flag for ${this.props.featureKey}`);
        const isFeatureEnabled = ldclient.variation(this.props.featureKey, this.props.defaultValue);
        this.setState({ isFeatureEnabled });
    });
}
```

**Comment by apucacao** [comment]
Hi @jasonbarry ,

`LDClient.initialize()` should only be called once in your application. We've been thinking about making the client a proper singleton, or allow multiple distinct instances, but for now, as you've found out, calls to `initialize` will affect existing clients, so it should be invoked once.

Here are a couple of approaches that we use ourselves, and which only require initializing the client once:

- Wait until the `ready` event before rendering the application and expose the client instance via a specific module. Depending on your use-case this might not be ideal if you need to make the app render as quickly as possible since you'll need to wait for the initial feature flag request to LaunchDarkly to complete, but it is simple.

- Initialize the LD client once in your root component and attach the instance to the [React context](https://facebook.github.io/react/docs/context.html).

Also here are a few resources from our community which you might find useful:

- [TrueCar/react-launch-darkly](https://github.com/TrueCar/react-launch-darkly/): a set of component helpers to add support for LaunchDarkly to your React.js app.
- [yusinto/ld-redux](https://github.com/yusinto/ld-redux/): a library to integrate LaunchDarkly with React and Redux.

We also have a few open-source example applications:
- [launchdarkly/saga-feature-flow](https://github.com/launchdarkly/saga-feature-flow): demonstrates how to use our SDK with React and Redux and redux-saga; we wrote a [blog post](http://blog.launchdarkly.com/implementing-feature-flags-in-single-page-apps-using-react-and-redux-saga/) too.
- A [photo browser application](https://github.com/launchdarkly/photo-browser) which also uses React and Redux.

Let me know if that helps, and if you have any other questions. 🙂

Cheers,
Alexis

**Comment by jasonbarry** [comment]
@apucacao thanks for the detailed write-up! Feel free to either close this issue or leave it open, whichever fits your workflow.

**Comment by tdeekens** [comment]
You could also have a look at [flopflip](https://github.com/tdeekens/flopflip). Another flexible library integrating with LaunchDarkly for feature toggling.

**Comment by thomasryu** [comment]
Hi, just as an update, is `initialize` still required to be called only once in my application? 
Thank you.

**Comment by thomasryu** [comment]
@apucacao do you know whether this behavior was updated? Or is `initialized` still required to be called once per application?

**Comment by eli-darkly** [comment]
@thomasryu - The intended usage for the JS SDK is always to keep a single LDClient instance around. Since calling `initialize` opens a new HTTP connection to LaunchDarkly, you don't want to do that any more often than necessary.

However, this particular issue was in the context of using the SDK from a React component. If that's what you are doing, you may want to look at our [React SDK](https://github.com/launchdarkly/react-client-sdk) (really a React wrapper for the JS SDK) which is intended to simplify the setup process and the interface in general for React apps.

If you have a different concern, it'd be helpful to know more details about what you're doing.
