### ISSUE TITLE
On 'error' event, provide `error` as event object when available

### ISSUE THREAD

**Issue by ravangen** [launchdarkly/js-client#58]
When an error occurs, it generally is logged to `console` and an `error` event is emitted. When emitted, it would be great if the source error object was sent to the callback. This way the callback function can elect to do something useful with the error instead of just knowing one occurred. 

An example where this could be applied, is forwarding these errors to an error collection system.

**Comment by apucacao** [comment]
Hi @ravangen ,

Thanks for raising this. That would indeed be very convenient, and we're in fact planning on improving error handling in this library.

We did just that recently for our [Node.js library](https://github.com/launchdarkly/node-client) and I'm curious to know if something like that would work for you. The library now either logs the error _or_ emits an `error` event if an `error` handler is attached. We also added custom error objects so that it's easier as a consumer to determine what happened.

**Comment by ravangen** [comment]
Yes, a similar change to that made in the Node.js library would satisfy this request.

Having specific error objects for different scenarios would help aggregate errors. It may be beneficial to also capture the details of the error where possible for debugging.

Thanks!
