### ISSUE TITLE
Server-side rendering support?

### ISSUE THREAD

**Issue by mickeyreiss-visor** [launchdarkly/js-client#65]
What is the recommended practice for using this SDK in a server-side rendering scenario, where XHR is not available?

Similar issue in the raven-js SDK: https://github.com/getsentry/raven-js/issues/951

**Comment by apucacao** [comment]
Hi @mickeyreiss-visor ,

We recommend combining the Node.js SDK with the client-side SDK for server-side rendering.

From a high-level — assuming you use express.js or something similar — it looks like this:
1. initialize the Node SDK as part of your server app
1. when a request comes in, grab the flag settings for the current user and pass those values to the server-side rendering code
1. [bootstrap the client-side SDK](https://docs.launchdarkly.com/docs/js-sdk-reference#section-bootstrapping) with the flag values for the current user

Bootstrapping the client-side SDK this way has two benefits:
- you can render the UI on the server with the correct flag values for the current user
- it causes SDK initialization to be practically instantaneous

Hope that helps. Let me know if you have any other questions 😃

**Comment by Askadias** [comment]
Having the following error on server client initialization in case of React Server-Side Rendering:
![image](https://user-images.githubusercontent.com/4466951/83270343-0443a400-a1d1-11ea-9a77-a9aacd519df4.png)

**Comment by eli-darkly** [comment]
@Askadias Thank you for reporting this, but in the future could you please file a new issue rather than commenting on a closed one that's more than two years old? Also, I think you've filed it in the wrong repository— the code you've screenshotted is not part of `js-client-sdk`; it appears to be part of the server-side Node SDK, specifically its logic for evaluating feature flag rules, which is not something `js-client-sdk` does at all.
